=== CMS-Enterprise/eAPD/api/schemas/apd.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "apd.json",
  "type": "object",
  "required": [
    "name",
    "activities",
    "federalCitations",
    "incentivePayments",
    "keyPersonnel",
    "narrativeHIE",
    "narrativeHIT",
    "narrativeMMIS",
    "previousActivityExpenses",
    "previousActivitySummary",
    "programOverview",
    "stateProfile",
    "years"
  ],
  "properties": {
    "_id": { "type": "string" },
    "name": { "type": "string" },
    "createdAt": { "$ref": "definitions.json#/definitions/optionalFullDate" },
    "updatedAt": { "$ref": "definitions.json#/definitions/optionalFullDate" },
    "stateId": { "type": "string" },
    "status": { "type": "string" },
    "__v": { "type": "number" },
    "activities": {
      "type": "array",
      "items": { "$ref": "activity.json" }
    },
    "federalCitations": { "$ref": "federalCitations.json" },
    "incentivePayments": { "$ref": "incentivePayments.json" },
    "keyPersonnel": { "$ref": "keyPersonnel.json" },
    "narrativeHIE": { "type": "string" },
    "narrativeHIT": { "type": "string" },
    "narrativeMMIS": { "type": "string" },
    "previousActivityExpenses": { "$ref": "previousActivityExpenses.json" },
    "previousActivitySummary": { "type": "string" },
    "programOverview": { "type": "string" },
    "stateProfile": { "$ref": "stateProfile.json" },
    "years": {
      "type": "array",
      "items": { "type": "string" }
    }
  },
  "additionalProperties": false
}

=== CMS-Enterprise/eAPD/api/seeds/test/03-finalAPD.json
{
  "name": "MN-1936-08-03-HITECH-APD",
  "activities": [],
  "federalCitations": {},
  "incentivePayments": {
    "ehAmt": {},
    "ehCt": {},
    "epAmt": {},
    "epCt": {}
  },
  "keyPersonnel": [],
  "narrativeHIE": "",
  "narrativeHIT": "",
  "narrativeMMIS": "",
  "previousActivityExpenses": {},
  "previousActivitySummary": "",
  "programOverview": "",
  "stateProfile": {
    "medicaidDirector": { "name": "", "email": "", "phone": "" },
    "medicaidOffice": {
      "address1": "",
      "address2": "",
      "city": "",
      "state": "",
      "zip": ""
    }
  },
  "years": []
}

=== CMS-Enterprise/eAPD/api/seeds/test/4001.json
{
  "name": "AZ-1865-12-06-HITECH-APD",
  "activities": [
    {
      "id": 4110,
      "alternatives": "",
      "contractorResources": [
        {
          "description": "",
          "end": "",
          "hourly": {
            "data": {
              "2019": {
                "hours": "",
                "rate": ""
              },
              "2020": {
                "hours": "",
                "rate": ""
              }
            },
            "useHourly": false
          },
          "hourlyData": [],
          "id": 9900,
          "name": "",
          "start": "",
          "totalCost": 0,
          "years": {
            "1865": 0,
            "1866": 0
          }
        }
      ],
      "costAllocation": {},
      "costAllocationNarrative": {
        "methodology": "",
        "2019": {
          "otherSources": "none"
        },
        "2020": {
          "otherSources": "none"
        }
      },
      "description": "",
      "expenses": [],
      "fundingSource": false,
      "name": "",
      "objectives": [],
      "plannedEndDate": "",
      "plannedStartDate": "",
      "schedule": [],
      "standardsAndConditions": {
        "doesNotSupport": "",
        "supports": ""
      },
      "statePersonnel": [],
      "summary": "",
      "quarterlyFFP": {}
    }
  ],
  "federalCitations": {},
  "incentivePayments": {
    "ehAmt": {},
    "ehCt": {},
    "epAmt": {},
    "epCt": {}
  },
  "keyPersonnel": [],
  "narrativeHIE": "",
  "narrativeHIT": "",
  "narrativeMMIS": "",
  "previousActivityExpenses": {},
  "previousActivitySummary": "",
  "programOverview": "",
  "stateProfile": {
    "medicaidDirector": { "name": "", "email": "", "phone": "" },
    "medicaidOffice": {
      "address1": "",
      "address2": "",
      "city": "",
      "state": "",
      "zip": ""
    }
  },
  "years": []
}
